name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript compilation check
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test -- --coverage --watchAll=false

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        fail_ci_if_error: false

  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint TypeScript/JavaScript
      run: npm run lint

    - name: Check TypeScript formatting
      run: npm run format:check

  build-and-package:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: [frontend-tests, lint-and-format]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build card
      run: npm run build

    - name: Validate build output
      run: |
        if [ ! -f "emergency-alerts-card.js" ]; then
          echo "❌ Build output not found"
          exit 1
        fi
        if [ ! -f "emergency-alerts-card.js.map" ]; then
          echo "❌ Sourcemap not found"
          exit 1
        fi
        echo "✅ Build output validated (with sourcemaps)"

    - name: Display build info
      run: |
        echo "Build size:"
        ls -lh emergency-alerts-card.js
        echo "Sourcemap size:"
        ls -lh emergency-alerts-card.js.map

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: card-build
        path: |
          emergency-alerts-card.js
          emergency-alerts-card.js.map
          hacs.json
          README.md
          LICENSE
        retention-days: 30

    - name: Archive build artifacts for download
      uses: actions/upload-artifact@v4
      with:
        name: emergency-alerts-card
        path: |
          emergency-alerts-card.js
          emergency-alerts-card.js.map
        retention-days: 90 