name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build card
      run: npm run build

    - name: Validate build output
      run: |
        if [ ! -f "emergency-alerts-card.js" ]; then
          echo "❌ Build output not found"
          exit 1
        fi
        if [ ! -f "emergency-alerts-card.js.map" ]; then
          echo "❌ Sourcemap not found"
          exit 1
        fi
        echo "✅ Build output validated (with sourcemaps)"

    - name: Display build info
      run: |
        echo "Build size:"
        ls -lh emergency-alerts-card.js
        echo "Sourcemap size:"
        ls -lh emergency-alerts-card.js.map

    - name: Run tests
      run: npm test -- --coverage --watchAll=false

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          emergency-alerts-card.js
          emergency-alerts-card.js.map
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-files
        path: |
          emergency-alerts-card.js
          emergency-alerts-card.js.map
        retention-days: 90 