name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build card
      run: npm run build

    - name: Run tests
      run: npm test -- --coverage --watchAll=false

    - name: Create release package
      run: |
        # Create release directory
        mkdir -p release
        
        # Copy required files for HACS
        cp dist/emergency-alerts-card.js release/
        cp hacs.json release/
        cp README.md release/
        
        # Create tar.gz package
        cd release
        tar -czf ../emergency-alerts-card-${{ github.ref_name }}.tar.gz *
        cd ..
        
        # Create zip package (alternative format)
        cd release
        zip -r ../emergency-alerts-card-${{ github.ref_name }}.zip *
        cd ..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          emergency-alerts-card-${{ github.ref_name }}.tar.gz
          emergency-alerts-card-${{ github.ref_name }}.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-packages
        path: |
          emergency-alerts-card-*.tar.gz
          emergency-alerts-card-*.zip
        retention-days: 90 